db:
  token:
  url:
  org:
  bucket: datalogger
  measurement1: group1
  measurement2: group2
  measurement3: group3
  measurement4: group4
  measurement5: group5
  measurement6: group6

app:
  port: 8080
