
db:
  token: zKS9tRvJyzSOjZcz9MWwCUlzY9uk9IIYsFsKt_4VyjusSCEewt0fEANggT-bEIX2E-gXVx1NmqrYfeUUfxSdJA==
  url: http://localhost:8086
  org: ea
  bucket: amita
  measurement1: group1
  measurement2: group2
  measurement3: group3
  measurement4: group4
  measurement5: group5

app:
  port: 8080
