
db:
  token: w5UzZyYrcDztOtVZroRtHdpRPn4ItAKh7yUJ30mmkG6eFJIkFWuN3s4ppIjX4RhGHGf3lO2Ihyk-w8guTJ5yTA==
  url: http://192.168.242.152:8086
  org: amt
  bucket: datalogger
  measurement1: group1
  measurement2: group2
  measurement3: group3
  measurement4: group4
  measurement5: group5
  measurement6: group6

app:
  port: 8080
