package services

type AutoGenerated struct {
	DATALOGID string `json:"DATALOG ID"`
	BATTERYID string `json:"BATTERY ID"`
	T1        string `json:"T1"`
	T2        string `json:"T2"`
	T3        string `json:"T3"`
	T4        string `json:"T4"`
	T5        string `json:"T5"`
	T6        string `json:"T6"`
	T7        string `json:"T7"`
	T8        string `json:"T8"`
	T9        string `json:"T9"`
	T10       string `json:"T10"`
	T11       string `json:"T11"`
	T12       string `json:"T12"`
	T13       string `json:"T13"`
	T14       string `json:"T14"`
	T15       string `json:"T15"`
	T16       string `json:"T16"`
	T17       string `json:"T17"`
	T18       string `json:"T18"`
	T19       string `json:"T19"`
	T20       string `json:"T20"`
	T21       string `json:"T21"`
	T22       string `json:"T22"`
	T23       string `json:"T23"`
	T24       string `json:"T24"`
	T25       string `json:"T25"`
	T26       string `json:"T26"`
	T27       string `json:"T27"`
	T28       string `json:"T28"`
	T29       string `json:"T29"`
	T30       string `json:"T30"`
	T31       string `json:"T31"`
	T32       string `json:"T32"`
	T33       string `json:"T33"`
	T34       string `json:"T34"`
	T35       string `json:"T35"`
	T36       string `json:"T36"`
	T37       string `json:"T37"`
	T38       string `json:"T38"`
	T39       string `json:"T39"`
	T40       string `json:"T40"`
	T41       string `json:"T41"`
	T42       string `json:"T42"`
	T43       string `json:"T43"`
	T44       string `json:"T44"`
	T45       string `json:"T45"`
	T46       string `json:"T46"`
	T47       string `json:"T47"`
	T48       string `json:"T48"`
}
